name: ameko_app
description: "Ameko - Custom Keyboard Marketplace"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  # Network
  dio: ^5.3.2

  # DI
  get_it: ^8.2.0

  # Functional
  dartz: ^0.10.1

  # Logging
  logger: ^2.6.2

  # Env
  flutter_dotenv: ^5.1.0

  # Forms
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0

  # Storage
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.0.0

  # Network connectivity
  connectivity_plus: ^7.0.0

  # UI
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.12
  google_fonts: ^6.3.2

  # WebView (for VNPAY payment flow)
  flutter_inappwebview: ^6.1.5

  # SignalR
  signalr_netcore: ^1.3.7

  # Navigation
  go_router: ^14.6.3
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter

  # Deep Links & URL Launching
  url_launcher: ^6.3.1
  app_links: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/svg/
    - assets/images/
